//3) Solicite dois valores (supostamente distintos) e apresente qual
// é o maior valor
algoritmo "semnome"

var
       n1:real
       n2: real
inicio

       escreva("Digite um número: ")
       leia(n1)

       escreva("Digite outro número: ")
       leia(n2)

       se (n1 > n2) entao
          escreva("O primeiro número é maior, ", n1)
         senao
          escreva("O segundo é o maior, ", n2)
       fimse

fimalgoritmo

