algoritmo "semnome"

var
     n1: inteiro


inicio

    escreval("Digite um número entre 1-12:")
    leia(n1)

    escolha(n1)
       caso 1
         escreval("Janeiro")
      caso 2
         escreval("fevereiro")
      caso 3
         escreval("Março")
      caso 4
         escreval("Abril")
      caso 5
           escreval("Maio")
      caso 6
           escreval("Junho")
      caso 7
           escreval("Julho")
      caso 8
           escreval("Agosto")
      caso 9
           escreval("Setembro")
      caso 10
           escreval("Outubro")
      caso 11
         escreval("Novembro")
      caso 12
         escreval("Dezembro")
      fimescolha
fimalgoritmo

