algoritmo "semnome"

var
       n1:real
       n2: real
inicio

       escreva("Digite um número: ")
       leia(n1)

       escreva("Digite outro número: ")
       leia(n2)

       se (n1 > n2) entao
          escreval("A subtração deles é: ", n1-n2)
          escreval("A multiplicação deles é: ", n1*n2)
         senao
          escreval("A subtração deles é: ", n2-n1)
          escreval("A multiplicação deles é: ", n1*n2)
       fimse

fimalgoritmo

