// Construa um algoritmo que leia e apresente a soma
// de 5 números fornecidos pelo usuário.
algoritmo "semnome"

var
   nota1: real
   nota2: real
   nota3: real
   nota4: real
   nota5: real
   media: real
inicio
   escreva("Digite a 1° nota: ")
   leia(nota1)
   escreva("Digite a 2° nota: ")
   leia(nota2)
   escreva("Digite a 3° nota: ")
   leia(nota3)
   escreva("Digite a 4° nota: ")
   leia(nota4)
   escreva("Digite a 5° nota: ")
   leia(nota5)


   escreva("O resultado é: ",(nota1+nota2+nota3+nota4+nota5))
fimalgoritmo

