// Informado 3 números, apresente a soma do primeiro com o
// terceiro, multiplicando pelo segundo.
algoritmo "semnome"

var
   nota1: inteiro
   nota2: inteiro
   nota3: inteiro
   media: inteiro
inicio
   escreva("Digite a 1° nota: ")
   leia(nota1)
   escreva("Digite a 2° nota: ")
   leia(nota2)
   escreva("Digite a 3° nota: ")
   leia(nota3)


   media<-(nota1+nota3)*nota2

   escreva("O resultado é: ",media)
fimalgoritmo

