// Conhecido 3 números inteiros, apresente o resultado
// da multiplicação dos mesmos
algoritmo "semnome"

var
   nota1: inteiro
   nota2: inteiro
   nota3: inteiro
   media: inteiro
inicio
   escreva("Digite a 1° nota: ")
   leia(nota1)
   escreva("Digite a 2° nota: ")
   leia(nota2)
   escreva("Digite a 3° nota: ")
   leia(nota3)


   media<- (nota1*nota2*nota3)

   escreva("A multiplicação dos 3 números é: ",media)
fimalgoritmo

